#!/bin/bash

# Create and activate venv named "env"
python3 -m venv env
source env/bin/activate

# Install dependencies into "env"
python3 -m pip install -r requirements.txt

# Run python script and pass along arguments
python3 generate_releases_internal.py "$@"

# Check the exit status
if [ $? -ne 0 ]; then
    echo "generate_releases Python script failed. Exiting."
    exit 1
fi

# Deactivate "env"
deactivate