#!/bin/bash

# Create and activate venv named "env"
python3 -m venv env
source env/bin/activate

# Install dependencies into "env"
python3 -m pip install -r requirements.txt

# Run python script and pass along arguments
python3 stats_internal.py "$@" 

# Deactivate "env"
deactivate