#!/bin/bash

# Check if there are uncommited changes
# generate_releases uses git stash several times, so they'd be lost
uncommitted_changes=$(git diff-index HEAD --);
if [ -n "$uncommitted_changes" ] # If uncommited_changes is not empty
then
    echo 'There are uncommited changes. Please commit or stash them before running this script.';
    exit 1;
fi

# Pull Release tags
echo 'Pulling...'
git pull;

# Update release files
echo 'Generating release files...'
./generate_releases;
if [ $? -ne 0 ]; then
    echo "generate_releases Python script failed. Exiting."
    exit 1
fi
echo 'Pushing new release files...'
git add .;
git commit -m "Update script: Updated release files";
git push;

# Record stats
echo 'Recording stats...'
./stats record;
if [ $? -ne 0 ]; then
    echo "stats bash script failed. Exiting."
    exit 1
fi
echo 'Pushing new stats...'
git add .;
git commit -m "Update script: Recorded stats";
git push;

echo 'Done!'