#!/bin/bash

# Check if there are uncommited changes
# generate_appcasts uses git stash several times, so they'd be lost
uncommitted_changes=$(git diff-index HEAD --);
if [ -n "$uncommitted_changes" ] # If uncommited_changes is not empty
then
    echo 'There are uncommited changes. Please commit or stash them before running this script.';
    exit 1;
fi

# Pull Release tags
echo 'Pulling...'
git pull;

# Update appcast files
echo 'Generating appcasts...'
python3 ./generate_appcasts;
echo 'Pushing new appcasts...'
git add .;
git commit -m "Update script: Updated appcasts";
git push;

# Record stats
echo 'Recording stats...'
./stats record;
echo 'Pushing new stats...'
git add .;
git commit -m "Update script: Recorded stats";
git push;

echo 'Done!'