#!/bin/bash

# Check if there are uncommited changes
# generate_appcasts uses git stash several times, so they'd be lost
uncommitted_changes=$(git diff-index HEAD --);
if [ -n "$uncommitted_changes" ] # If uncommited_changes is not empty
then
    echo 'There are uncommited changes. Please commit or stash them before running this script.';
    exit 1;
fi

# Pull Release tags
git pull;

# Update appcast files
python3 ./generate_appcasts;
git add .;
git commit -m "Updated appcasts";
git push;

# Record stats
python3 ./stats record
git add .;
git commit -m "Recorded stats"
git push