//
//  Use this file to import your target's public headers that you would like to expose to Swift.
//

#import "Logging.h"
#import "Constants.h"
#import "VectorUtility.h"
#import "MathObjc.h"
#import "DisplayLinkTypes.h"
#import "AnimatorDeclarations.h"
#import "Config.h"
#import "ScrollConfigObjC.h"
#import "PointerConfigObjC.h"
#import "SubPixelator.h"
#import "VectorSubPixelator.h"
#import "SharedUtility.h"
#import "HelperUtility.h"
#import "CircularBuffer.h"
#import "Modifiers.h"
#import "Remap.h"
#import "PointerSpeed.h"
#import "PolynomialRegression.h"
#import "PolyFitObjC.h"
#import "IOHIDAccelerationTableBridge.hpp"
#import "EventUtility.h"
#import "GlobalEventTapThread.h"
#import "DeviceManager.h"
#import "SymbolicHotKeys.h"
#import "OutputCoordinator.h"
#import "TouchSimulator.h"
#import "NSDictionary+Additions.h"
#import "NSAttributedString+Additions.h"
#import "License.h"
#import "Locator.h"
#import "NSAnimationManager.h"
#import "Hyperlink.h"
#import "HelperServices.h"
#import "Shorthands.h"
#import "SFSymbolStrings.h"
#import "NSView+Additions.h"
#import "NSScreen+Additions.h"
#import "Device.h"
#import "ButtonModifiers.h"
#import "ScrollModifiers.h"
#import "NSString+Additions.h"
#import "MacAddress.h"
#import "MFCoding.h"
#import "NSData+Additions.h"
#import "Localization.h"
#import "LogitechActivator.h"
#import "AccessibilityCheck.h"
#import "KeyCaptureMode.h"
#import "CGSSpace.h"
#import "PointerFreeze.h"


#import "DevToggles.h" /// [May 2025] We don't need this in release builds

//#import <CocoaLumberjack/CocoaLumberjack.h> /// Importing CocoaLumberjack/Swift with CocoaPods breaks my project. Can't use macros when importing this.
