//
//  Use this file to import your target's public headers that you would like to expose to Swift.
//

#import "Constants.h"
#import "VectorUtility.h"
#import "MathObjc.h"
#import "WannaBePrefixHeader.h"
#import "DisplayLink.h"
#import "AnimatorDeclarations.h"
#import "Config.h"
#import "ScrollConfigObjC.h"
#import "PointerConfigObjC.h"
#import "SubPixelator.h"
#import "VectorSubPixelator.h"
#import "SharedUtility.h"
#import "HelperUtility.h"
#import "CircularBuffer.h"
#import "RemapSwizzler.h"
#import "ScrollModifiers.h"
#import "ModifierManager.h"
#import "TransformationManager.h"
#import "ModifiedDrag.h"
#import "Scroll.h"
#import "PointerSpeed.h"
#import "PolynomialRegression.h"
#import "PolyFitObjC.h"
#import "IOHIDAccelerationTableBridge.hpp"
#import "EventUtility.h"
#import "GlobalEventTapThread.h"
#import "DeviceManager.h"
#import "ButtonLandscapeAssessor.h"
#import "Actions.h"
#import "OutputCoordinator.h"
#import "GestureScrollSimulator.h"
#import "NSMutableDictionary+Additions.h"
#import "NSAttributedString+Additions.h"
#import "Licensing.h"

//#import <CocoaLumberjack/CocoaLumberjack.h> /// Importing CocoaLumberjack/Swift with CocoaPods breaks my project. Can't use macros when importing this.
